### ISSUE TITLE
I cannot access to the Graphics menu

### ISSUE THREAD

**Issue by lemmings189** [BlueStaggo/MCDiverge#17]
> 

      Minecraft has crashed!      
      ----------------------      

Minecraft has stopped running because it encountered a problem.

If you wish to report this, please copy this entire text and email it to support@mojang.com.
Please include a description of what you did when the error occured.

// Bruh moment.
--- BEGIN ERROR REPORT fbf93fc1 --------
Generated 03/08/23 14:42

Minecraft: Minecraft Diverge 0.3
OS: Windows 10 (amd64) version 10.0
Java: 1.8.0_381, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
LWJGL: 2.9.3
OpenGL: Intel(R) UHD Graphics version 4.6.0 - Build 30.0.100.9955, Intel

java.lang.ArrayIndexOutOfBoundsException: -1
	at fr.d(GameSettings.java:321)
	at ay.initPage(GuiOptions.java:61)
	at ay.a(GuiOptions.java:36)
	at bh.a(GuiScreen.java:92)
	at net.minecraft.client.Minecraft.a(Minecraft.java:406)
	at ay.a(GuiOptions.java:77)
	at bh.a(GuiScreen.java:65)
	at bh.e(GuiScreen.java:115)
	at bh.d(GuiScreen.java:100)
	at net.minecraft.client.Minecraft.i(Minecraft.java:1032)
	at net.minecraft.client.Minecraft.run(Minecraft.java:510)
	at java.lang.Thread.run(Unknown Source)
--- END ERROR REPORT bc7d6939 ----------

**Comment by BlueStaggo** [comment]
I keep seeing people get this crash and I'm not very sure why this is happening. I'll try to fix it for a 0.3 hotfix.

**Comment by BlueStaggo** [comment]
Fixed in 0.3.1
