### ISSUE TITLE
Not compatible with opengl < 4.3

### ISSUE THREAD

**Issue by mc665** [BlueStaggo/MCDiverge#33]
**Starting up SoundSystem...
Initializing LWJGL OpenAL
    (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
OpenAL initialized.

java.lang.RuntimeException: Failed to get skin!
	at ThreadGetSkin.run(ThreadGetSkin.java:128)
Caused by: java.lang.Exception: Failed to get UUID: Server responded with non-200 HTTP code.
	at ThreadGetSkin.run(ThreadGetSkin.java:42)
java.lang.IllegalStateException: Function is not supported
	at org.lwjgl.BufferChecks.checkFunctionAddress(BufferChecks.java:58)
	at org.lwjgl.opengl.GL43.glMultiDrawElementsIndirect(GL43.java:847)
	at net.mine_diver.smoothbeta.client.render.VboPool.drawAll(VboPool.java:221)
	at net.mine_diver.smoothbeta.client.render.RenderRegion.a(RenderRegion.java:41)
	at n.a(WorldRenderer.java:658)
	at n.a(WorldRenderer.java:631)
	at n.a(WorldRenderer.java:551)
	at px.a(EntityRenderer.java:559)
	at px.updateCameraAndRender(EntityRenderer.java:452)
	at net.minecraft.client.Minecraft.run(Minecraft.java:635)
	at java.lang.Thread.run(Unknown Source)
Stopping!

SoundSystem shutting down...
    Author: Paul Lamb, www.paulscode.com**
    
    
This is terrible for my gl 3.3 potato computer ☠
Beta Rework - enhancement

**Comment by Sunflames0** [comment]
this is getting fixed in the next pre-release with the addition of SmoothBeta(multidraw) toggle

**Comment by Sunflames0** [comment]
it'll be disabled by default on unsupported devices

**Comment by BlueStaggo** [comment]
Yeah, as Sunflames0 said, this is getting fixed in 1.0-a10.
